global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gerador-nota-fiscal
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]

  - job_name: consumidores-simulados
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["consumidores-simulados:8081"]
